### ISSUE TITLE
komorebi:プログラム作成

### ISSUE THREAD

**Issue by shimiura** [shimiura/sallonesatellite#12]
- 口金挙ってきたら

**Comment by shimiura** [comment]
- りょうじできそう？

**Comment by ryojiric** [comment]
さっきラインに動画あげました

**Comment by shimiura** [comment]
最終的には点滅のパターンとか、8pinoにプログラム書き込みまでお願いします

**Comment by ryojiric** [comment]
ごめん、プログラムは、シンペイか本丸にお願いしたい！

**Comment by shimiura** [comment]
ほんまる、夕焼けのついでにお願いできる？
LED3つを適当なパターンで、1個ずつ付けたり消したりする感じ。

**Comment by honmaru** [comment]
komorebi プログラム
[komorebi.zip](https://github.com/shimiura/sallonesatellite/files/200849/komorebi.zip)
