### ISSUE TITLE
yuyake: プログラム作成

### ISSUE THREAD

**Issue by shimiura** [shimiura/sallonesatellite#9]

**Comment by shimiura** [comment]
* 時間経過に合わせて、色合いを変化させる。

**Comment by shimiura** [comment]
- 参考になるかも
[田中健司](http://mathrax.com/contents/page5288)

**Comment by shimiura** [comment]
- 本丸、これいつごろ検討完了しそう！？

**Comment by shimiura** [comment]
- いつごろ検討完了しそう！？
- このレポジトリに適当にプログラム挙げといてもらえる量産の時に助かります。

**Comment by honmaru** [comment]
[yuyake2.zip](https://github.com/shimiura/sallonesatellite/files/201198/yuyake2.zip)

**Comment by honmaru** [comment]
[Adafruit_NeoPixel.zip](https://github.com/shimiura/sallonesatellite/files/201200/Adafruit_NeoPixel.zip)

**Comment by honmaru** [comment]
[yuyake1 2.zip](https://github.com/shimiura/sallonesatellite/files/201205/yuyake1.2.zip)

**Comment by shimiura** [comment]
[yuyake_demo.zip](https://github.com/shimiura/sallonesatellite/files/201209/yuyake_demo.zip)

**Comment by honmaru** [comment]
夕焼けFIX
黄色から赤色への変化
[yuyake_fix 2.zip](https://github.com/shimiura/sallonesatellite/files/201250/yuyake_fix.2.zip)
